version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partnership
    ports:
      - "5434:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" --address ":9000"

  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres


volumes:
  minio_data:
  postgres_data:


# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     restart: unless-stopped
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: qwerty1231
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

#   postgres:
#     image: postgres:latest
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: partnership
#     ports:
#       - "5434:5432"

#   minio:
#     image: minio/minio:latest
#     container_name: minio
#     restart: unless-stopped
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: minioadmin
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     volumes:
#       - minio_data:/data
#     command: server /data --console-address ":9001" --address ":9000"

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - ES_JAVA_OPTS=-Xms1g -Xmx1g
#       - xpack.security.enabled=false # Nonaktifkan security untuk dev
#       - xpack.security.http.ssl.enabled=false
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     volumes:
#       - es_data:/usr/share/elasticsearch/data

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.15.3
#     container_name: kibana
#     environment:
#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch

# volumes:
#   mongo_data:
#   minio_data:
#   postgres_data:
#   es_data:
